spring.application.name=blissmap


#URL: jdbc:postgresql://212.132.97.24:5432/pmokhammad
#username: pmokhammad
#password: qfP94j9woo8dISPS


spring.datasource.url=jdbc:postgresql://localhost:5432/blissmap
spring.datasource.username=Vafo
spring.datasource.password=hallo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



